name: RCC files

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          
      - name: Install RCC
        run: sudo apt install qtbase5-dev-tools

      - name: default RCC
        run: |
          echo '<!DOCTYPE RCC><RCC version="1.0">' > ./default/theme.qrc
          echo '<qresource prefix="/base/themes/default">' >> ./default/theme.qrc
          echo '    <file>charselect.ui</file>' >> ./default/theme.qrc
          echo '    <file>direct_connect_dialog.ui</file>' >> ./default/theme.qrc
          echo '    <file>favorite_server_dialog.ui</file>' >> ./default/theme.qrc
          echo '    <file>lobby.ui</file>' >> ./default/theme.qrc
          echo '    <file>options_dialog.ui</file>' >> ./default/theme.qrc
          echo '    <file>version</file>' >> ./default/theme.qrc
          echo '    <file>lobby_assets/down-arrow.png</file>' >> ./default/theme.qrc
          echo '    <file>lobby_assets/up-arrow.png</file>' >> ./default/theme.qrc
          echo '</qresource>' >> ./default/theme.qrc
          echo '</RCC>' >> ./default/theme.qrc
          echo '1' > version

      - name: compile RCC
        run: |
          cd default
          rcc -binary theme.qrc -o theme.rcc